Add to Person a createGreetingsForFriends method which will 
return an array of strings - each string in the array is a 
greeting generated by the createGreeting method. For example:

> var alfie = new Person('Alfie');
> var anushka = new Person('Anushka');
> var henrique = new Person('Henrique');
> alfie.addFriend(anushka);
> alfie.addFriend(henrique);
> alfie.createGreetingsForFriends();
["Yo Anushka! from Alfie.", "Yo Henrique! from Alfie."]

Do this without using a loop but by using map instead.


class Person {
	constructor(name, friends) {
		this.name = name;
		this.friends = [];
	}	
		addFriend(other) {
			this.friends.push(other);
		}
		createGreeting(other) {
			return 'Yo ' + other.name + '! from ' + this.name + '.';	
		}
		greet(other) {
			console.log(this.createGreeting(other));
		}
		createGreetingsForFriends() {
			var greetings = this.friends.map((x) => {
				return 'Yo ' + x.name + '! from ' + this.name + '.';
			});

			console.log(greetings);
		}
}

var alfie = new Person('Alfie');

var anushka = new Person('Anushka');

var henrique = new Person('Henrique');

alfie.addFriend(anushka);

alfie.addFriend(henrique);

alfie.createGreetingsForFriends();
